apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: mongodb
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: mongodb
    spec:
      containers:
      - env:
        - name: MONGO_INITDB_DATABASE
          value: sample
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: rootpassword
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        image: mongo:latest
        name: mongodb-container
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: mongodb-claim

        - mountPath: /docker-entrypoint-initdb.d
          name: mongodb-init
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: mongodb-claim
        persistentVolumeClaim:
          claimName: mongodb-claim
      - name: mongodb-init
        configMap:
          name: mongo-initial
